[package]
name = "merge_files"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
flatgeobuf = { version = "4.2.1", default-features = false }
geozero = { version = "0.13.0", default-features = false, features = ["with-geojson"] }
