name: Deploy web

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: pavement_parking/web/package-lock.json

      - name: Build web app
        run: |
          cd pavement_parking/web
          npm ci
          npm run build --if-present

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pavement_parking/web/dist/
